```{r}
import numpy as np
from scipy import linalg
import os
```

# 类及函数封装

```{r}
def solve_sym(xtx, xty):
    L = linalg.cholesky(xtx)
    return linalg.lapack.dpotrs(L, xty)[0] 
```

我们使用递推公式获得矩阵$Z$

$$
\begin{array}{cc}
 & p=1 \\
\begin{array}{c}0\\1\end{array}& 
\left[\begin{array}{cc}
0\\
1
\end{array}\right]
\end{array} 
\Rightarrow
\begin{array}{cc}
 & p=2 \\
\begin{array}{c}0\\2\\1\\3\end{array}&
\left[\begin{array}{cc}
0&0\\
0&1\\
1&0\\
1&1
\end{array}\right]
\end{array}
\Rightarrow
\begin{array}{cc}
 & p=3 \\
\begin{array}{c}0\\4\\2\\6\\1\\5\\3\\7\end{array}&
\left[\begin{array}{ccc}
0&0&0\\
0&0&1\\
0&1&0\\
0&1&1\\
1&0&0\\
1&0&1\\
1&1&0\\
1&1&1
\end{array}\right]
\end{array}\quad \cdots \tag{2}
$$

- 上面$(2)$式中矩阵左侧的数字代表矩阵行向量的十进制数值.
- 从$(2)$式中可以看出，给矩阵左侧添加一列$0$得到的向量，其十进制值为原向量的二倍，给矩阵的左侧添加一列$1$得到的向量，其十进制值为原向量的二倍加一.
- 给$2^p*p$维$Z$矩阵左侧分别添加一列$0$和$1$，并按行拼接，即可得到$2^{(p+1)}*(p+1)$维$Z$矩阵.
- turnbits_rec函数即可实现此功能。

```{r}
def turnbits_rec(p):
    if(p==1):
        return np.array([[True, False],[True, True]])
    else:
        tmp1 = np.c_[ turnbits_rec(p - 1), 
                     np.array([False]*(2**(p - 1))).reshape((2**(p - 1), 1))] # Create False and then reshape.
        tmp2 = np.c_[ turnbits_rec(p - 1), 
                     np.array([True]*(2**(p - 1))).reshape((2**(p - 1), 1))] # Create True and then reshape.
        return np.r_[tmp1, tmp2]
```

```{r}
class BestSubsetRegress(object):
    """BestSubsetRegression

    A best subset regression based on Cp, AIC and cross validation.
    
    Attributes:
        x: A ndarray data of dependent variable.
        y: A ndarray data of independent variable.
        intercept: A boolean indicating if intercept is included in data.
        isCp: A boolean indicating if Cp is applied.
        isAIC: A boolean indicating if AIC is applied.
        isCV: A boolean indicating if cross validation is applied.
    """
    def __init__(self, x=0,  y=0, intercept=True, isCp=True, isAIC=True, isCV=True):
        self.n, self.p = x.shape
        if intercept:
            self.x = np.c_[np.ones((self.n, 1)), x] # If intercept, then generize a column which is all 1
        else:
            self.x = x
    
        self.ind_var = turnbits_rec(self.p) # Generate the matrix using the pre-defined function
        self.y = y
        self.xtx = np.dot(self.x.T, self.x)
        self.xty = np.dot(self.x.T, self.y)
        self.b = [] # Regression Coefficients
        
        # Parameters
        self.isCp = isCp
        self.isAIC = isAIC
        self.isCV = isCV
        self.intercept = intercept
        
    # Calculate Regression Coefficients
    def regress(self):
        self.b = [solve_sym(self.xtx[ind][:, ind], self.xty[ind]) # "ind" is the index of the variables.
                  for ind in self.ind_var]
        return self.b
    
    # Calculate CV statistics
    def Cp_AIC(self):
        self.b = BestSubsetRegress.regress(self)
        mse = [np.sum(np.dot(self.xtx[ind][:, ind], b_)*b_) 
               for ind, b_ in zip(self.ind_var, self.b)]
        rss = np.dot(self.y, self.y) - mse
        d = np.sum(self.ind_var, axis=1)
        self.Cp = rss + 2*d*rss[-1]/(self.n - self.p - 1) 
        self.AIC = self.n*np.log(rss) + 2*d
        
    # Performing Cross Validation
    def cvreg(self):
        K = 10
        indices = np.array_split(np.random.permutation(np.arange(0, self.n)), K) # Split the datasets into K folds.
    
        def cvk(ind, index): # "ind" is the index of the variables. "index" is the index of the index of the Kth fold.
            txx = self.xtx[ind][:, ind] - np.dot((self.x[index][:, ind]).T, 
                                                 self.x[index][:, ind])
            txy = self.xty[ind] - np.dot((self.x[index][:, ind]).T, 
                                         self.y[index])
            tcoe = solve_sym(txx, txy)
            return np.sum(
                (self.y[index] - np.dot(self.x[index][:, ind], tcoe))**2)
        self.cverr = np.sum(np.array(
            [[cvk(ind, index) for index in indices] 
             for ind in self.ind_var]), axis = 1)/self.n
        
    
    def bestsubsetregress(self):
        self.names = np.array(['x' + str(i) for i in range(1, self.p+1)])
        
        if self.isCp or self.isAIC:
            BestSubsetRegress.Cp_AIC(self)
            
        if self.isCp:
            min_id_Cp = np.argmin(self.Cp)
            if self.intercept:
                sub_names_Cp = np.insert(self.names[self.ind_var[min_id_Cp][1:]], 0, 'mu')
            else:
                sub_names_Cp = self.names[self.ind_var[min_id_Cp][1:]]
            sub_beta_Cp = self.b[min_id_Cp]
            print('The best subset and coeffecients under Cp:\n')
            print(dict(zip(sub_names_Cp, sub_beta_Cp)), '\n')
            
        if self.isAIC:
            min_id_AIC = np.argmin(self.AIC)
            if self.intercept:
                sub_names_AIC = np.insert(self.names[self.ind_var[min_id_AIC][1:]], 0, 'mu')
            else:
                sub_names_AIC = self.names[self.ind_var[min_id_AIC][1:]]
            sub_beta_AIC = self.b[min_id_AIC]
            print('The best subset and coeffecients under AIC:\n')
            print(dict(zip(sub_names_AIC, sub_beta_AIC)), '\n')
            
        if self.isCV:   
            BestSubsetRegress.cvreg(self)
            min_id_CV = np.argmin(self.cverr)
            if self.intercept:
                sub_names_CV = np.insert(self.names[self.ind_var[min_id_CV][1:]], 0, 'mu')
            else:
                sub_names_CV = self.names[self.ind_var[min_id_CV][1:]]
            sub_beta_CV = self.b[min_id_CV]
            print('The best subset and coeffecients under CV:\n')
            print(dict(zip(sub_names_CV, sub_beta_CV)), '\n')
```

# 结果

```{r}
#os.chdir()
x = np.loadtxt("./DataForRegression/x.txt", delimiter=",")
y = np.loadtxt("./DataForRegression/y.txt", delimiter=",")
regress = BestSubsetRegress(x, y)
regress.bestsubsetregress()
```

# 运行指标

所有模型的 Cp 统计量

```{r}
regress.Cp
```

所有模型的AIC

```{r}
regress.AIC
```

